anguage: node_js
node_js:
  - '12'
services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mini-koa:latest .
  - docker push mini-koa:latest